lineBot:
  nike:
    channelToken: ${nike-channelToken}
    channelSecret: ${nike-channelSecret}
  test:
    channelToken: ${test-channelToken}
    channelSecret: ${test-channelSecret}
  family:
    groupId: ${family-groupId-nike}
  
  